name: geofencing
description: A geofencing plugin for Flutter applications.
version: 0.0.1
author: Ben Konyi <bkonyi@google.com>
homepage: https://github.com/flutter/plugins

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: 0.4.5

flutter:
  plugin:
    androidPackage: io.flutter.plugins.geofencing
    pluginClass: GeofencingPlugin